### ISSUE TITLE
catch sqlite exceptions

### ISSUE THREAD

**Issue by tonykaralis** [tonykaralis/MoodMovies#12]
currently there is no exception handling

**Comment by tonykaralis** [comment]
most exceptions are now being caught but need to disaply a useful message when things fail

**Comment by tonykaralis** [comment]
Use snackbars. Dont take up space and they pop up when necessary

**Comment by PoLaKoSz** [comment]
I think this is the best place to answer to [this PR review question](https://github.com/tonykaralis/MoodMovies/pull/41#issuecomment-416193588).

Thank You for pointing out my mistake to be honest I was not fully concentrated to use try-catch when used DB access but I know this is a huge irresponsibility so I will fix it ASAP.

**Comment by tonykaralis** [comment]
This is perfect place for this.

And there is no problem with your commits, the more the better. A commit in my eyes should include a single change( fix, feature, etc). This may contain 1 or more files/ lines. E.g. of what is not a good commit( changing the entire colour scheme of the app as well as adding a new search function) the 2 are unrelated and better kept separate.

**Comment by tonykaralis** [comment]
Your last PR was fine. Lots of commits yes, but that is better in my eyes. Keep up the good work
