### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by PoLaKoSz** [tonykaralis/MoodMovies#19]
Hi!

A week ago I think finally understood what IoC meant for so I made some changes on the current code to use interfaces instead of hard coded classes.

If You want to take a look please [take a peek to this branch](https://github.com/PoLaKoSz/MoodMovies/tree/develop/dependency-injection). Any feedback appreciated.

**Comment by tonykaralis** [comment]
Hi,

Glad you are learning new things all the time. I took a look at the branch and it looks good. This is exactly what I wanted to do, I just dont have enough time in the day.. Is it ready to merge? If yes make a PR. Good clean code 👍

**Comment by tonykaralis** [comment]
This is done.
