### ISSUE TITLE
Increasing performance

### ISSUE THREAD

**Issue by PoLaKoSz** [tonykaralis/MoodMovies#28]
Hi!

I use an old and weak PC (2 core, 2,8GHz CPU) so I really feel when something get slower. I think there are unnecessary SQLite queries which cause this problem for me. Should I investigate it?

**Comment by tonykaralis** [comment]
Hi Tom, yes I am aware of the performance issues when accessing the db. I have made a lot of the functions and got them to work, but have not optimised them yet. There are definitely a few calls that are unnecessary. I am planning on working on that this week, if you would like to you can in investigate and make any changes you feel to another branch. Send the link to the branch and ill take a look. That would save me a lot of time. Thanks

**Comment by PoLaKoSz** [comment]
I started to add a `CurrentUser` parameter to ViewModel constructors and I thought I will ask You what do you think about loading the UI, displaying a "Logging in" `StartLoadingMessage` and prevent the user to change menu while no account provided with an API Key?

**Comment by tonykaralis** [comment]
Sounds like a good idea. Only thing I dont like doing is disabling buttons and controls. Do you have any other suggestions for blocking them from  navigating??

**Comment by PoLaKoSz** [comment]
I just did a little test and I disabled manually the Search chip in XAML and it only just changed the cursor type (from pointer to default) so nothing greyed out (but I thing greying out would be the best solution for this).

**Comment by tonykaralis** [comment]
Okay i see your point. Let's go with your suggestion for now. I'll try and think of a neater way of setting up this logging in story.

**Comment by tonykaralis** [comment]
How is the db optimisation going?

**Comment by PoLaKoSz** [comment]
I hope it won't take that long, but I want to finish it before 12 AM.

**Comment by tonykaralis** [comment]
Don't worry @PoLaKoSz  no rush ;)

**Comment by PoLaKoSz** [comment]
Hi @Tony!

You can find the end result [in this branch](https://github.com/PoLaKoSz/MoodMovies/tree/dev/increase-performance).

**Comment by tonykaralis** [comment]
I cant seem to find your commits on this?

**Comment by tonykaralis** [comment]
Raise a pull request for the increase performance branch. That should be fine. Ill make a few more changes this weekend that might speed it up even more. With the logging-in-message branch also raise a pull request, however on the weekend I will see if I have enough time to take a look at implementing a different idea I have. Otherwise looking good.

**Comment by PoLaKoSz** [comment]
Yes, definitely faster, All right, thank You!

**Comment by PoLaKoSz** [comment]
Can you give me a hint what I missed? I am curious. :)

**Comment by tonykaralis** [comment]
Sure, just give me a sec.

**Comment by tonykaralis** [comment]
Sorry @PoLaKoSz my brai is dead from this past weeks work. I thought there were still optimizations needed but it seems I cant find any more. You must have got them all 👍
