### ISSUE TITLE
View not displaying users form DB

### ISSUE THREAD

**Issue by tonykaralis** [tonykaralis/MoodMovies#32]
When trying to add a user, it fails to add showing the message 'A user with the Api Key already exists'. However does not show me any users. @PoLaKoSz

**Comment by PoLaKoSz** [comment]
I used [DB Browser for SQLite](https://sqlitebrowser.org/) when tested the account creation, maybe something wrong with it.

**Comment by PoLaKoSz** [comment]
[MoodMoviesDB.zip](https://github.com/tonykaralis/MoodMovies/files/2190413/MoodMoviesDB.zip)

Change the extension from `.zip` to `.db`. This is my current DB.

**Comment by tonykaralis** [comment]
Is it working for you? Did you change anything in the db manually?

**Comment by PoLaKoSz** [comment]
Yes, in the c8f34e5607a0c47458472c407344814bde8cadd5 commit I deleted the `Poster_Cache` column from the DB

> Removed Poster_Cache property from Movies entity because it is now auto generated (removed fron SQLite .db resource too)

**Comment by tonykaralis** [comment]
Ok, thats fine. I have that change as well. First issue is that when loading up the mainviewmodel if it cant find a user that is set to current user it crashes when passing the api key to easyclient(api key will be null since no current user). This d68bc549f5f9367f27a1eef21c9de890eadb919f fixes that issue. Now there is another issue I am tracking.

**Comment by PoLaKoSz** [comment]
Interesting. I checked out to 345b43c87cb2b388caf10f745ee74e69dd7c5c5e (this is before your fix commit). Deleted the only one user. Started the app and it just notified me that can't loaded any user. I made one, set to current and worked fine.

**Comment by tonykaralis** [comment]
try searching for a movie?

**Comment by PoLaKoSz** [comment]
Sorry. I was distrait. I was able to reproduce the bug.

**Comment by tonykaralis** [comment]
Probelm is we are calling GetUsers method and firinf event that nobody is listening to yet(searchviewmodel etc have not been created yet). I think we will leave thi for now, I want to add a page at startup where the user will be able to select/ create account before proceeding to the app. This is the best way in my opinion. I am going to reset the current branch to before the pull request and then work on it tomorrow. 👍

**Comment by tonykaralis** [comment]
You have learnt alot from when you first started with this project, I have much more confidence in you now! Keep going 👍
