### ISSUE TITLE
Creating a new user does not display the correct messages

### ISSUE THREAD

**Issue by tonykaralis** [tonykaralis/MoodMovies#35]
Steps to reproduce:
- input just 1 field (eg name)
- hit create new user

Message displayed:
Invalid Api Key.

Message should be:
Please fill in all fields

**Comment by tonykaralis** [comment]
Fixed 9df558087d3b03113bee42fb138bbcc9b46ffdc0 here.

**Comment by PoLaKoSz** [comment]
Sorry for that.

**Comment by tonykaralis** [comment]
No Worries
