### ISSUE TITLE
Account creation

### ISSUE THREAD

**Issue by tonykaralis** [tonykaralis/MoodMovies#36]
@PoLaKoSz I re designed and recreated the entire logging in process. I hop you like it.

I have not done anything with th user control page yet though. I will be changing that design as well, and make it easier for someone to switch accounts(more user friendly etc) 

Everything should work etc the usercontrol viewmodel(i havent got there yet).

I also need to add some validation to the email and password boxes. Currently loading will fail if password does not contain at least 1 letter. If you want to test and play around with it remember this hehe. I will fix this as soon as possible, or you can take a look. Please try not to make any changes to db because that damn sqlite gave me a lot of trouble today. 

Also there is a lot more translation stuff if you feel up to it 👍 

Hope you like the look.

**Comment by PoLaKoSz** [comment]
I get these Exceptions when starting the app:
> Exception thrown: 'System.Data.Entity.Core.ProviderIncompatibleException' in EntityFramework.dll
SQLite error (1): no such column: Extent1.Model
Exception thrown: 'System.Data.SQLite.SQLiteException' in System.Data.SQLite.dll
Exception thrown: 'System.Data.SQLite.SQLiteException' in System.Data.SQLite.dll
Exception thrown: 'System.Data.Entity.Core.EntityCommandExecutionException' in EntityFramework.dll
Exception thrown: 'System.Data.Entity.Core.EntityCommandExecutionException' in EntityFramework.dll
Exception thrown: 'System.Data.Entity.Core.EntityCommandExecutionException' in EntityFramework.dll
Exception thrown: 'System.Data.DataException' in EntityFramework.dll
Exception thrown: 'System.Data.DataException' in EntityFramework.dll
Exception thrown: 'System.Data.DataException' in mscorlib.dll
Exception thrown: 'System.Data.DataException' in mscorlib.dll
Exception thrown: 'System.Data.DataException' in mscorlib.dll

After calling the `var user = await _offlineDb.GetCurrentUSer();` function the app stucks at the `Loading..` message and never hit the `InjectCurrentUser(user);` method.

I previously added a `User_Email` and a `User_Password` field to the Users table.

This is my DB now: [MoodMoviesDB.zip](https://github.com/tonykaralis/MoodMovies/files/2194732/MoodMoviesDB.zip) - change the extension to `.db`

**Comment by tonykaralis** [comment]
Are you changing the th in the moodmovies appdata folder? This can cause problems with sqlite and ef6. There are no migration setup yet so you have to delete the th in moodmovies and then run the app again and it will build the new database.

**Comment by tonykaralis** [comment]
Sqlite is very touchy so for now, I know it's not practical but it is in production so just delete db in appdata and run fresh. We will need to figure out something for migrations at some point.

**Comment by PoLaKoSz** [comment]
- UI awesome!
- After the successful registration the registration page not cleared

**Comment by PoLaKoSz** [comment]
> We will need to figure out something for migrations at some point.

Yesterday I tried to make migrations with EF6 but I wasn't able to do it (only the first one was made - maybe it couldn't connect to the DB) so I think it would be better if You take a look at it too how to make migrations with EF6 on an SQLite DB because I don't think it is impossible I just didn't find the right path.

I started to make a migrator (I don't think it will be **so** advanced but I will need something for the future) in case if none of us make EF6 to migrate properly.

**Comment by tonykaralis** [comment]
I agree with you, I will take a look at migrations as wel.. Do you want to show me your migrator?

**Comment by PoLaKoSz** [comment]
I just started about an hour ago. If you open up the Library.Example you will see how I imagine (this is kind of integration of [Laravel migrations](https://laravel.com/docs/5.5/migrations) to C#).
[SQLite-Migrator.zip](https://github.com/tonykaralis/MoodMovies/files/2195598/SQLite-Migrator.zip)

**Comment by tonykaralis** [comment]
Merge accepted and fixed this 

> After the successful registration the registration page not cleared

Let me know if anything is breaking, I haven't tested anything hah

**Comment by tonykaralis** [comment]
I am closing this for now.
