### ISSUE TITLE
DB migrations

### ISSUE THREAD

**Issue by PoLaKoSz** [tonykaralis/MoodMovies#38]
I made some progress with the migrator ([You can find here the full source code](https://github.com/PoLaKoSz/SQLite-Migrator)) but I found a better solution called [FluentMigrator](https://github.com/fluentmigrator/fluentmigrator/).

**Comment by PoLaKoSz** [comment]
I was wrong. The mentioned library does not support 2 important command in SQLite:
- [delete column](https://github.com/fluentmigrator/fluentmigrator/blob/e48c6bb1fcb30a107de0c2eb0bae49d7946e7ff4/src/FluentMigrator.Runner.SQLite/Generators/SQLite/SQLiteGenerator.cs#L64) - [Issue 812](https://github.com/fluentmigrator/fluentmigrator/issues/812)
- [rename column](https://github.com/fluentmigrator/fluentmigrator/blob/e48c6bb1fcb30a107de0c2eb0bae49d7946e7ff4/src/FluentMigrator.Runner.SQLite/Generators/SQLite/SQLiteGenerator.cs#L59)

`SQLiteGenerator.cs` file from the **v4.0.0.-alpha118** (*Jul 17, 2018*) release.

**Comment by tonykaralis** [comment]
That's a pain.. I guess we will just make sure we don't migrate down. Its a pitty because its quite a neat library

**Comment by tonykaralis** [comment]
@PoLaKoSz is there anywhere I can chat to you about a job? I would rather not do that here. Email?

**Comment by PoLaKoSz** [comment]
Yes, You can send it here: `polakosztom@gmail.com`.

**Comment by PoLaKoSz** [comment]
Good news:
[Successfully implemented](https://github.com/PoLaKoSz/fluentmigrator/tree/dev/SQLite) the `Delete.Column(string columnName)` but I think this is not the best implementation so I will wait a bit and try to come up with a better one. And of course I will (re)write the Unit and Integration tests to verify my code.

**Comment by fubar-coder** [comment]
I was notified that you stumbled upon the fact that SQLite doesn't support the deletion of columns. Your solution seems to work good enough™ and I'd gladly accept a PR 😁 .

**Comment by PoLaKoSz** [comment]
Sorry I deleted my post because I was ashamed how stupid this solution is. It can't even be tested and I don't want to trash the library with that code.

I don't have to much experience with collaboration and GitHub etiquette but if I have a question / idea about implementing my "code" more better should I ask it in the [issue 812](https://github.com/fluentmigrator/fluentmigrator/issues/812)?

**Comment by fubar-coder** [comment]
@PoLaKoSz No problem. Issue fluentmigrator/fluentmigrator#812 is indeed the best place to discuss this problem. Maybe we can even discuss different options and their pros and cons. Your PR should (ideally) target the master branch and I'd port it to develop and release new versions.
